# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e11f47996107e10907bf64c647c216a5c0c045cb4dcde20ff1829de595cd80dcad375b4c115afefc86b7132c538ad73b6dc65ca1af97a31258fbd44963e4c3bb

test:
  secret_key_base: eae5b7538316b910ac1b96a4d109bb17d9b97e2493667d1077fd75336fdee7c4a337845b0873edbd69d26774708c4ad071421c275ba4926c7d06cb10ca7f52b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
